package com.example.terminal

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView
import com.google.gson.Gson
import org.json.JSONObject
import kotlin.concurrent.thread

class CheckoutActivity : AppCompatActivity() {

    private val tv_msg by lazy { findViewById<TextView>(R.id.res_msg) }
    private val img_msg by lazy { findViewById<ImageView>(R.id.res_img) }

    private fun onResponse(response: JSONObject, act: CheckoutActivity) {
        val totalAmountPaid = response.get("amountPaid");
        writeText("PAYMENT SUCCESSFULL!")
        appendText("Total paid ${totalAmountPaid} €")
        setImg(R.drawable.baseline_done_24)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_checkout)

        val textV = intent.getStringExtra("text") ?: ""

        try {
            val checkoutObj = Gson().fromJson(textV, Checkout::class.java)
            checkoutUser(checkoutObj, applicationContext, this::onResponse, this)
        } catch (e: java.lang.Exception) {
            tv_msg.text =
                "QR CODE parsing error.\nAre you using the QRCode generated by the ACME App ?"
            img_msg.setImageResource(R.drawable.outline_error_outline_24)
        }
    }

    fun appendText(value: String) {
        runOnUiThread { tv_msg.append(value + "\n") }
    }

    fun writeText(value: String) {
        runOnUiThread { tv_msg.text = value + "\n" }
    }

    fun setImg(img: Int) {
        runOnUiThread {
            img_msg.setImageResource(img)
        }
    }
}