package com.example.terminal

import android.content.DialogInterface
import android.content.Intent
import android.net.Uri
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.ImageView
import android.widget.ListView
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import com.google.gson.Gson
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.util.*
import kotlin.concurrent.thread

class CheckoutActivity : AppCompatActivity() {

    private val tv_msg by lazy { findViewById<TextView>(R.id.res_msg) }
    private val img_msg by lazy { findViewById<ImageView>(R.id.res_img) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_checkout)

        val textV = intent.getStringExtra("text") ?: ""

        try {
            val checkoutObj = Gson().fromJson(textV, Checkout::class.java)
            thread {
                pay(this, checkoutObj)
            }
        } catch (e: java.lang.Exception) {
            tv_msg.text =
                "QR CODE parsing error.\nAre you using the QRCode generated by the ACME App ?"
            img_msg.setImageResource(R.drawable.outline_error_outline_24)
        }
    }

    fun appendText(value: String) {
        runOnUiThread { tv_msg.append(value + "\n") }
    }

    fun writeText(value: String) {
        runOnUiThread { tv_msg.text = value + "\n" }
    }

    fun setImg(img: Int) {
        runOnUiThread {
            img_msg.setImageResource(img)
        }
    }
}